import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar,Footer } from "./components";
import { ThemeProvider } from "next-themes";
import { Toaster } from 'sonner';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider attribute="class">
      <main className="dark:bg-nft-dark bg-white min-h-screen sm:tracking-normal overflow-hidden">
      <Toaster richColors position="bottom-right"/>
      <Navbar/>
      <div className="pt-65">{children}</div>
      <Footer/>
      </main>
      </ThemeProvider>
      </body>
    </html>
  );
}
